<?php /*

[literal]
ClassDescription[actionscript]=ActionScript
ClassDescription[ada]=Ada
ClassDescription[apache]=Apache Log
ClassDescription[applescript]=AppleScript
ClassDescription[asm]=ASM
ClassDescription[asp]=ASP
ClassDescription[autoit]=AutoIt
ClassDescription[bash]=Bash
ClassDescription[blitzbasic]=BlitzBasic
ClassDescription[bnf]=bnf
ClassDescription[c]=C
ClassDescription[csharp]=C#
ClassDescription[c_mac]=C (Mac)
ClassDescription[cpp]=C++
ClassDescription[cpp-qt]=C++ (QT)
ClassDescription[caddcl]=CAD DCL
ClassDescription[cadlisp]=CAD Lisp
ClassDescription[cfdg]=CFDG
ClassDescription[cfm]=ColdFusion
ClassDescription[css]=CSS
ClassDescription[d]=D
ClassDescription[delphi]=Delphi
ClassDescription[diff]=Diff
ClassDescription[div]=DIV
ClassDescription[dos]=DOS
ClassDescription[eiffel]=Eiffel
ClassDescription[eztemplate]=eZ template
ClassDescription[fortran]=Fortran
ClassDescription[freebasic]=FreeBasic
ClassDescription[gml]=GML
ClassDescription[groovy]=Groovy
ClassDescription[html4strict]=HTML
ClassDescription[ini]=INI
ClassDescription[inno]=Inno
ClassDescription[io]=Io
ClassDescription[java]=Java
ClassDescription[java5]=Java(TM) 2 Platform Standard Edition 5.0
ClassDescription[javascript]=Javascript
ClassDescription[latex]=LaTeX
ClassDescription[lisp]=Lisp
ClassDescription[lua]=Lua
ClassDescription[matlab]=Matlab M
ClassDescription[mpasm]=Microchip Assembler
ClassDescription[reg]=Microsoft Registry
ClassDescription[mirc]=mIRC Scripting
ClassDescription[mysql]=MySQL
ClassDescription[nsis]=NSIS
ClassDescription[objc]=Objective C
ClassDescription[ocaml-brief]=OCaml
ClassDescription[ocaml]=OCaml
ClassDescription[oobas]=OpenOffice.org Basic
ClassDescription[oracle8]=Oracle 8 SQL
ClassDescription[pascal]=Pascal
ClassDescription[perl]=Perl
ClassDescription[php]=PHP
ClassDescription[php-brief]=PHP
ClassDescription[plsql]=PL/SQL
ClassDescription[python]=Python
ClassDescription[qbasic]=QBasic/QuickBASIC
ClassDescription[rails]=Rails
ClassDescription[robots]=robots.txt
ClassDescription[ruby]=Ruby
ClassDescription[sas]=SAS
ClassDescription[scheme]=Scheme
ClassDescription[sdlbasic]=sdlBasic
ClassDescription[smalltalk]=Smalltalk
ClassDescription[smarty]=Smarty
ClassDescription[sql]=SQL
ClassDescription[tsql]=T-SQL
ClassDescription[tcl]=TCL
ClassDescription[text]=Text
ClassDescription[thinbasic]=thinBasic
ClassDescription[idl]=Uno Idl
ClassDescription[vbnet]=vb.net
ClassDescription[vhdl]=VHDL
ClassDescription[vb]=Visual Basic
ClassDescription[visualfoxpro]=Visual Fox Pro
ClassDescription[winbatch]=Winbatch
ClassDescription[xpp]=X++
ClassDescription[xml]=XML
ClassDescription[z80]=ZiLOG Z80 Assembler

[VersionManagement]
DefaultVersionHistoryLimit=100000000

*/ ?>
